### ISSUE TITLE
issue with other mods items not taking apothic affixs 

### ISSUE THREAD

**Issue by TheIronwitch** [Daripher/Apothic-Curios#4]
mine and slash items as well as items from artifacts don't take apoptotic infusions

**Comment by TheIronwitch** [comment]
[message.txt](https://github.com/Daripher/Apothic-Curios/files/13721493/message.txt)

**Comment by drakray** [comment]
Got a similar crash with Artifacts's Running Shoes on exploration
I was just wandering and it crashed
https://pastebin.com/7rawq2WL

```
Description: Ticking entity

java.lang.RuntimeException: Failed to locate any affixes for running_shoes{null} with category LootCategory[curios:feet] and rarity LootRarity{apotheosis:common}.
	at dev.shadowsoffire.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:73) ~[apotheosis-1.20.1-7.2.0.jar%23733!/:7.2.0] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:42) ~[apotheosis-1.20.1-7.2.0.jar%23733!/:7.2.0] {re:classloading}
	at dev.shadowsoffire.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:36) ~[apotheosis-1.20.1-7.2.0.jar%23733!/:7.2.0] {re:classloading}
```
MC 1.20.1
Neoforge 47.1.83
Apotheosis 7.2.0
ApothicCurios 1.0.3
[..._ManyOthers™_...]

**Comment by JWTHDYTWA** [comment]
ANY curios in Reforging Table causes client crash. Wtf?

**Comment by Daripher** [comment]
> ANY curios in Reforging Table causes client crash. Wtf?

Only if you don't add enough affixes for each rarity

**Comment by drakray** [comment]
So it might be because of interaction with Apothic Addition or mods that add lots of stuff like Iron's Spellbook and such?

**Comment by NovaLynxie** [comment]
Hi there, I was looking for any issue reports and stumbled across this one.
I feel like you may be onto something, @drakray, as I have Apothic Additions in my modpack setup and kept getting the exact kinds of crashes mentioned in this issue report. For me, though, it was arrow{null}.
My crash report if you need additional data to help find a fix.
Crash Report: https://gist.github.com/NovaLynxie/4e924a2839ce7d3827779c3c0c164afd
Update: Scratch that. I only had Apothic Curios installed with my pack, and it still threw the same error.

**Comment by drakray** [comment]
Temporary fix is to set removeErroringEntities = true in WORLD/serverconfig/forge-server.toml
This allow the world to be used, but might cause other problems?
